version: '3.0'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    kafka:
      image: wurstmeister/kafka:2.12-2.5.0
      container_name: kafka
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: redis
    container_name: rediscache
    ports:
    - 6380:6379
    networks:
      - spring-net

  spring-testcontainers-app:
    image: spring-testcontainers-app
    container_name: spring-testcontainers-app
    build: .
    restart: always
    environment:
      REDIS_HOST: rediscache
      REDOS_PORT: 6379
    ports:
      - 8080:8080
    depends_on:
      - redis
    networks:
      - spring-net

networks:
  spring-net: