version: '3.0'

services:
  redis-docker:
    image: redis
    container_name: redis-digital
    ports:
      - 6379:6379

  kafka-server:
    image: bitnami/kafka
    ports:
      - "9092:9092"
#    expose:
#      - '9092'
    volumes:
      - "kafka_data:/bitnami/kafka"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "test:1:1"


#  debezium:
#    image: debezium/connect
#    environment:
#      BOOTSTRAP_SERVER: kafka-server:9092
#      GROUP_ID: 1
#      CONFIG_STORAGE_TOPIC: connect_configs
#      OFFSET_STORAGE_TOPIC: connect_offsets
#    depends_on:
#      - kafka-server
#    ports:
#      - 8083:8083

volumes:
  kafka_data:
    driver: local
  debezium_data:
    driver: local