version: '3.8'

services:
  redis-docker:
    image: redis
    container_name: redis-digital
    ports:
      - "6379:6379"

# zookeeper 있는 설정

  zookeeper:
    image: zookeeper:3.8.1
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181 # 컨테이너 내부의 포트
      ZOOKEEPER_TICK_TIME: 2000 # 주키퍼가 클러스터를 구성할 때 동기화를 위한 기본 시간을 지정
      ZOOKEEPER_INIT_LIMIT: 5 # quorum 내의 zookeeper 서버들이 leader에 연결할 때 사용되는 최대 시간을 제한하기 위해 사용하는 timeout 단위
      ZOOKEEPER_SYNC_LIMIT: 2 # 서버가 leader로부터 얼마나 sync에 뒤쳐질 수 있는지를 제한하는 timeout 단위
    ports:
      - "2181:2181"

  kafka-1:
    image: confluentinc/cp-kafka:7.3.1
    platform: linux/amd64
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 # 연결하고자 하는 주키퍼의 이름과 포트
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:19092, EXTERNAL://localhost:9092 # 외부에 접속하기 위한 리스너 설정
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL # 도커 내부에서 사용할 리스너 이름 지정.
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT # 보안을 위한 프로토콜 매핑. KAFKA_ADVERTISED_LISTENERS 와 함께 key/value 로 매핑
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3 # Replication factor 를 지정.
      KAFKA_NUM_PARTITIONS: 3 # 파티션 숫자
      ALLOW_PLAINTEXT_LISTENER: yes # 암호화되지 않은 리스너의 접근 권한 여부

  kafka-2:
    image: confluentinc/cp-kafka:7.3.1
    platform: linux/amd64
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:19093, EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
      ALLOW_PLAINTEXT_LISTENER: yes

  kafka-3:
    image: confluentinc/cp-kafka:7.3.1
    platform: linux/amd64
    ports:
      - "9094:9094"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:19094, EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
      ALLOW_PLAINTEXT_LISTENER: yes

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8081:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:19092, kafka-2:19093, kafka-3:19094
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

