spring:
  config:
    activate:
      on-profile: "devtools_apply"
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
  mvc:
    log-request-details: true
  codec:
    log-request-details: true
#devtools 사용이유
#1. 캐시 비활성화(탬플릿엔진)
#2. auto start (java 소스 변경시) - 자동 재시작이 되지 않으므로 밑에 내용처럼 적용하면 프로젝트를 재시작하는것보단 빠름..
#3. LiveReload(html 등 정적소스 변경시)
#4. 전역 설정

#spring.devtools.restart
#1. 설정 > 빌드, 실행, 배포 > 빌드 도구 > 컴파일러 > 프로젝트 자동 빌드 - 체크
#2. 설정 > 고급 설정 > 컴파일러: 개발된 애플리케이션이 현재 실행 중인 경우에도 auto-make가 시작되도록 허용 - 체크
#3. 자바 소스 수정 후 빌드 - 프로젝트 다시 빌드를 선택하면 빠르게 실행 됨.

#spring.devtools.livereload
#탬플릿을 사용하는 경우엔 true로 주면 auto-reload 됨. 단, 사용하는 브라우저에 LiveReload 확장프로그램 설치 필요.