ALTER TABLE players ALTER COLUMN joined TYPE VARCHAR(11);
ALTER TABLE players ALTER COLUMN birth TYPE VARCHAR(11);
ALTER TABLE staffs ALTER COLUMN joined TYPE VARCHAR(11);
ALTER TABLE staffs ALTER COLUMN birth TYPE VARCHAR(11);
